name: Run isort

on: [push, pull_request]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --editable ".[dev]"
    - name: isort
      uses: isort/isort-action@v1.0.0
