name: Pylint

on: [push, pull_request]

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Analysing the code with pylint
        run: |
           poetry run pylint wintertoo --fail-under=10.00
